export const carsList = [
    {
        id: '001',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Altima',
        trim: '2.5 SV Sedan',
        price: '24,570',
        financePerMonth: '416',
        cashDown: '2,457',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1N4AL3AP1HC123170',
        mileage: '0',
        extColor: 'Gun Metallic',
        details:
            "This car delivers affordable transportation inside an attractive four door package with class leading standard safety features.  Nissan prioritized comfort and style by including: fully automatic headlights, an overhead console, and a blind spot monitoring system.  Under the hood you'll find a 4 cylinder engine with more than 170 horsepower, and for added security, dynamic Stability Control supplements the drivetrain.",
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Altima-6eedce710a0a00f957998a6b9f156119.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Altima-b6449d4f46212c99819b97195861b70cx.jpg?alt=media&token=d26796e9-30f4-4248-b631-0cacdc46b9d8'
    },
    {
        id: '007',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2014',
        make: 'Nissan',
        model: 'Versa',
        trim: 'SV Sedan',
        price: '10,991',
        financePerMonth: '164',
        cashDown: '1,099',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '3N1CN7APXEL833790',
        mileage: ' 35,978',
        extColor: 'Blue Onyx',
        details:
            'It offers great fuel economy and a broad set of features! This 4 door, 5 passenger sedan still has fewer than 40,000 miles! All of the premium features expected of a Nissan are offered, including: front bucket seats, remote keyless entry, and a split folding rear seat. Smooth gearshifts are achieved thanks to the efficient 4 cylinder engine, and for added security, dynamic Stability Control supplements the drivetrain.',
        url:
            'https://drcertificationdemo.cms.dealer.com/used/Nissan/2014-Nissan-Versa-6eea84c10a0a00f957998a6b91623d60.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Versa-93355dc709a8a2f9c807283fb1156343x.jpg?alt=media&token=99579ec4-6c8c-43b3-bf4b-696ebcbceadc'
    },
    {
        id: '002',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Altima',
        trim: '2.5 S Sedan',
        price: '22,100',
        financePerMonth: '375',
        cashDown: '2,210',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1N4AL3AP4HN307121',
        mileage: '0',
        extColor: 'CAYENNE RE',
        details:
            'This vehicle rocks its class with 4-cylinder efficiency and distinctive styling! Top features include a split folding rear seat, tilt steering wheel, cruise control, and air conditioning. It features an automatic transmission, front-wheel drive, and a 2.5 liter 4 cylinder engine.',
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Altima-6ee655b90a0a00f957998a6bde342d8d.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Altima-7f28b47534665e726729c8b7eedc77edx.jpg?alt=media&token=aaf8714e-8d34-4ffc-ae46-392d851344ae'
    },
    {
        id: '003',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Altima',
        trim: '2.5 SL Sedan',
        price: '30,275',
        financePerMonth: '513',
        cashDown: '3,028',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1N4AL3AP0HC150733',
        mileage: '0',
        extColor: 'Pearl White',
        details:
            'Providing great efficiency and utility! Nissan paid particular attention to efficiency and practicality with the following features: leather upholstery, a built-in garage door transmitter, and power seats. Smooth gearshifts are achieved thanks to the 2.5 liter 4 cylinder engine, and for added security, dynamic Stability Control supplements the drivetrain.',
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Altima-6ee792e30a0a00f957998a6bbf97185c.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Altima-3ebcf85d4aec5b3e8805b177c939d222x.jpg?alt=media&token=3c1ff426-bb17-4779-b7b5-f6c98da04778'
    },
    {
        id: '004',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Altima',
        trim: '2.5 S Sedan',
        price: '22,140',
        financePerMonth: '',
        cashDown: '',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '',
        mileage: '0',
        extColor: 'Glacier White',
        details:
            "It offers the latest in technological innovation and style. Nissan prioritized comfort and style by including: delay-off headlights, power door mirrors, and a split folding rear seat. Under the hood you'll find a 4 cylinder engine with more than 170 horsepower, and for added security, dynamic Stability Control supplements the drivetrain.",
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Altima-6ee698eb0a0a00f957998a6b51c3d8fe.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Altima-eb00f48b97e3ef70cd3b1bf035037668x.jpg?alt=media&token=c97c8ff5-99bf-4866-9ae1-662b7d76f854'
    },
    {
        id: '005',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Rogue',
        trim: 'SL SUV',
        price: '29,406',
        financePerMonth: '496',
        cashDown: '2,941',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: 'JN8AT2MT2HW381231',
        mileage: '0',
        extColor: 'Monarch Orange',
        details:
            'A comfortable ride with plenty of style! It includes leather upholstery, a power rear cargo door, an overhead console, and air conditioning. It features a front-wheel-drive platform, an automatic transmission, and a 2.5 liter 4 cylinder engine.',
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Rogue-6ef7ac550a0a00f957998a6b20025135.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Rogue-612d795e1b9b27bae4df3a012b484a90x.jpg?alt=media&token=acd32fd4-5e6c-4b0c-9ced-c9ff699ddfc3'
    },
    {
        id: '006',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'new',
        year: '2017',
        make: 'Nissan',
        model: 'Rogue',
        trim: 'S SUV',
        price: '23,218',
        financePerMonth: '393',
        cashDown: '2,322',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: 'JN8AT2MT0HW134693',
        mileage: '0',
        extColor: 'Palatial Ruby',
        details:
            'Both practical and stylish! Nissan prioritized fit and finish as evidenced by: variably intermittent wipers, an overhead console, and a split folding rear seat. Smooth gearshifts are achieved thanks to the efficient 4 cylinder engine, and for added security, dynamic Stability Control supplements the drivetrain.',
        url:
            'https://drcertificationdemo.cms.dealer.com/new/Nissan/2017-Nissan-Rogue-6ef712b90a0a00f957998a6ba70df218.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Rogue-Palatial%20Ruby-NBF-66%2C20%2C31-640-en_US.jpg?alt=media&token=168f6a1f-a532-4bcd-9e5b-5df5a8c48579'
    },
    {
        id: '008',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2014',
        make: 'Nissan',
        model: 'Altima',
        trim: '2.5 S Sedan',
        price: '14,281',
        financePerMonth: '211',
        cashDown: '1,428',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1N4AL3APXEC134602',
        mileage: '32,371',
        extColor: 'Super Black',
        details:
            "A safe vehicle to haul your most precious cargo! This vehicle has achieved Certified Pre-Owned status, by passing Nissan's comprehensive certification process, including a comprehensive 156 point inspection! This model accommodates 5 passengers comfortably, and provides features such as: front bucket seats, cruise control, and air conditioning. It features a front-wheel-drive platform, an automatic transmission, and a 2.5 liter 4 cylinder engine.",
        url:
            'https://drcertificationdemo.cms.dealer.com/certified/Nissan/2014-Nissan-Altima-6eebeeb50a0a00f957998a6b7915c21a.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Altima-ebc1368144ac9fdbbc318bd67a9a549bx.jpg?alt=media&token=b6c67e06-c019-460f-9a0e-88e04cbb5383'
    },
    {
        id: '009',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2014',
        make: 'Honda',
        model: 'Accord',
        trim: 'EX-L V-6 Coupe',
        price: '21,991',
        financePerMonth: '321',
        cashDown: '2,199',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1HGCT2B8XEA002523',
        mileage: '13,736',
        extColor: 'Black',
        details:
            "ROIMOTORS.com Sales reps are knowledgeable and professional. We'd be happy to answer any questions that you may have. Call 1-800-555-2800 now to schedule a test drive or for more information on this vehicle.",
        url:
            'https://drcertificationdemo.cms.dealer.com/used/Honda/2014-Honda-Accord-6ee39ba30a0a00f957998a6b076eda04.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Honda-Accord-f169d003424d86e46315d7f44da619f8x.jpg?alt=media&token=d4178727-45a7-43ad-be19-1bb81bbdccc9'
    },
    {
        id: '010',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2015',
        make: 'Honda',
        model: 'Accord',
        trim: 'LX Sedan',
        price: '17,881',
        financePerMonth: '260',
        cashDown: '1,788',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1HGCR2F3XFA201022',
        mileage: '31,103',
        extColor: 'Basque Red Pearl',
        details:
            "ROIMOTORS.com Sales reps are knowledgeable and professional. We'd be happy to answer any questions that you may have. Call 1-800-555-2800 now to schedule a test drive or for more information on this vehicle.",
        url:
            'https://drcertificationdemo.cms.dealer.com/used/Honda/2015-Honda-Accord-6ee91ded0a0a00f957998a6b4a6975b9.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Honda-Accord-2ec394f648fce4fd572112057ae300bfx.jpg?alt=media&token=5ad617e7-85a8-436e-851e-5bf2c26cf4be'
    },
    {
        id: '011',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2013',
        make: 'Nissan',
        model: 'Rogue',
        trim: 'S AWD SUV',
        price: '15,582',
        financePerMonth: '230',
        cashDown: '1,558',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: 'JN8AS5MV7DW129006',
        mileage: '22,429',
        extColor: 'Silver',
        details:
            'Worthy equipment and features in an attainable package with perfect midsize proportions! With fewer than 25,000 miles on the odometer, this 4 door sport utility vehicle prioritizes comfort, safety and convenience. The following features are included: an outside temperature display, cruise control, and a split folding rear seat. It features all-wheel drive versatility, an automatic transmission, and a 2.5 liter 4 cylinder engine.',
        url:
            'https://drcertificationdemo.cms.dealer.com/used/Nissan/2013-Nissan-Rogue-6ef3bec80a0a00f957998a6be1fa7b25.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Nissan-Rogue-76c75675f984b7e5f433e48e84a4ef66x.jpg?alt=media&token=ba4b58a8-3277-41e3-9b67-bbda3d3416cb'
    },
    {
        id: '012',
        dealerName: 'ROI Motors - DR Certification',
        dealerStreet: '1 Howard Burlington',
        dealerState: 'VT',
        dealerZip: '05401',
        newOrUsed: 'used',
        year: '2016',
        make: 'Honda',
        model: 'Accord',
        trim: 'Touring Sedan',
        price: '28,991',
        financePerMonth: '416',
        cashDown: '2,899',
        creditScore: 'Excellent',
        financingMonth: '60',
        financingApr: '3.92',
        vin: '1HGCR3F97GA011819',
        mileage: '21,239',
        extColor: 'Crystal Black Pearl',
        details:
            "ROIMOTORS.com Sales reps are knowledgeable and professional. We'd be happy to answer any questions that you may have. Call 1-800-555-2800 now to schedule a test drive or for more information on this vehicle.",
        url:
            'https://drcertificationdemo.cms.dealer.com/used/Honda/2016-Honda-Accord-6eef4a2c0a0a00f957998a6ba1004f59.htm',
        imageUrl:
            'https://firebasestorage.googleapis.com/v0/b/universal-cars-browser.appspot.com/o/Honda-Accord-cb694a9586338996107fc5d64faec06cx.jpg?alt=media&token=b35e1eca-eee6-43b4-bcd9-d883bae22d46'
    }
];
